- name: Setup nginx
  ansible.builtin.apt:
    name: nginx-full
    state: latest

- name: Change config files
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Enable and start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers