- name: Setup nginx
  ansible.builtin.apt:
    name: nginx-full
    state: latest

- name: Change config file
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Enable and start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
