- name: Setup nginx
  ansible.builtin.apt:
    name: nginx-full
    state: latest
    update_cache: yes

- name: Change 'index.html' file
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
