- name: Download influxdb exporter
  ansible.builtin.get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/prometheus-influxdb-stats-exporter
    mode: '0777'
    owner: prometheus

- name: Copy service file
  ansible.builtin.copy:
    src: prometheus-influxdb-stats-exporter.service
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    owner: prometheus
  notify: Restart influxdb exporter

- name: Copy bind config
  ansible.builtin.template:
    src: prometheus-influxdb-stats-exporter.j2
    dest: /etc/default/prometheus-influxdb-stats-exporter
  notify: Restart influxdb exporter

- name: Start and enable influxdb stats exporter
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: yes
    daemon_reload: yes
