- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
    state: latest

- name: Enable haproxy
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: yes

- name: Copy config
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy