- name: Create directories
  ansible.builtin.file:
    path: /opt/grafana/provisioning/{{ item }}
    recurse: yes
    state: directory
  loop:
    - dashboards
    - datasources

- name: Copy grafana config
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini

- name: Copy dashboards
  ansible.builtin.copy:
    src: "{{ item }}.json"
    dest: /opt/grafana/provisioning/dashboards/{{ item }}.json
  loop:
    - main
    - rsyslog
    - mysql

- name: Copy default.yaml for dashboards
  ansible.builtin.copy:
    src: default.yaml
    dest: /opt/grafana/provisioning/dashboards/default.yaml

- name: Copy default.yaml for datasources
  ansible.builtin.template:
    src: default.yaml.j2
    dest: /opt/grafana/provisioning/datasources/default.yaml

- name: Create a grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
  notify: Restart grafana
