- name: Install prerequisites
  ansible.builtin.apt:
    name: software-properties-common
    state: latest

- name: Install grafana key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Install grafana repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: latest
    update_cache: yes

- name: Copy grafana config
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Start end enable grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- include_tasks: provisioning.yaml