{
 "title": "Main Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "VM's CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\", instance=\"alekseibahmatov-1:9100\", mode=\"system\", job=\"linux\"}[1m]) * 100",
     "legendFormat": "alekseibahmatov-1"
    },
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\", instance=\"alekseibahmatov-2:9100\", job=\"linux\", mode=\"system\"}[1m]) * 100",
     "legendFormat": "alekseibahmatov-2"
    },
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\", instance=\"alekseibahmatov-3:9100\", mode=\"system\", job=\"linux\"}[1m]) * 100",
     "legendFormat": "alekseibahmatov-3"
    }
   ]
  },
  {
   "title": "VM's Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"alekseibahmatov-1:9100\", job=\"linux\"} / node_memory_MemTotal_bytes{instance=\"alekseibahmatov-1:9100\", job=\"linux\"} * 100",
     "legendFormat": "alekseibahmatov-1"
    },
    {
     "expr": "(node_memory_Active_bytes{instance=\"alekseibahmatov-2:9100\", job=\"linux\"} * 100) / node_memory_MemTotal_bytes{instance=\"alekseibahmatov-2:9100\", job=\"linux\"}",
     "legendFormat": "alekseibahmatov-2"
    },
    {
     "expr": "(node_memory_Active_bytes{instance=\"alekseibahmatov-3:9100\", job=\"linux\"} * 100) / node_memory_MemTotal_bytes{instance=\"alekseibahmatov-3:9100\", job=\"linux\"}",
     "legendFormat": "alekseibahmatov-3"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"alekseibahmatov-1:9113\", job=\"nginx\"}",
     "legendFormat": "alekseibahmatov-1"
    },
    {
     "expr": "nginx_up{instance=\"alekseibahmatov-2:9113\", job=\"nginx\"}",
     "legendFormat": "alekseibahmatov-2"
    },
    {
     "expr": "nginx_up{instance=\"alekseibahmatov-3:9113\", job=\"nginx\"}",
     "legendFormat": "alekseibahmatov-3"
    }
   ]
  },
  {
   "title": "Bind Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"alekseibahmatov-1:9119\", job=\"bind\"}",
     "legendFormat": "alekseibahmatov-1"
    },
    {
     "expr": "bind_up{instance=\"alekseibahmatov-2:9119\", job=\"bind\"}",
     "legendFormat": "alekseibahmatov-2"
    },
    {
     "expr": "bind_up{instance=\"alekseibahmatov-3:9119\", job=\"bind\"}",
     "legendFormat": "alekseibahmatov-3"
    }
   ]
  },
  {
   "title": "Mysql Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"alekseibahmatov-1:9104\", job=\"mysql\"}",
     "legendFormat": "alekseibahmatov-1"
    },
    {
     "expr": "mysql_up{instance=\"alekseibahmatov-2:9104\", job=\"mysql\"}",
     "legendFormat": "alekseibahmatov-2"
    }
   ]
  },
  {
   "title": "HAProxy Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"alekseibahmatov-1:9101\"}",
     "legendFormat": "alekseibahmatov-1"
    },
    {
     "expr": "haproxy_up{instance=\"alekseibahmatov-2:9101\"}",
     "legendFormat": "alekseibahmatov-2"
    }
   ]
  },
  {
   "title": "Keepalived vrrp state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"alekseibahmatov-1:9165\"}",
     "legendFormat": "alekseibahmatov-1"
    },
    {
     "expr": "keepalived_vrrp_state{instance=\"alekseibahmatov-2:9165\"}",
     "legendFormat": "alekseibahmatov-1"
    }
   ]
  },
  {
   "title": "Keepalived Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_up{instance=\"alekseibahmatov-1:9165\"}",
     "legendFormat": "alekseibahmatov-1"
    },
    {
     "expr": "keepalived_up{instance=\"alekseibahmatov-2:9165\"}",
     "legendFormat": "alekseibahmatov-2"
    }
   ]
  },
  {
   "title": "DNS queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"alekseibahmatov-1:9119\", type=\"A\"}[1m]) * 100",
     "legendFormat": "A alekseibahmatov-1"
    },
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"alekseibahmatov-2:9119\", type=\"A\"}[1m]) * 100",
     "legendFormat": "A alekseibahmatov-2"
    }
   ]
  },
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"alekseibahmatov-1:9101\", server=\"agama-1\"}",
     "legendFormat": "agama-1"
    },
    {
     "expr": "haproxy_server_up{instance=\"alekseibahmatov-1:9101\", server=\"agama-2\"}",
     "legendFormat": "agama-2"
    },
    {
     "expr": "haproxy_server_up{instance=\"alekseibahmatov-2:9101\", server=\"agama-3\"}",
     "legendFormat": "agama-3"
    },
    {
     "expr": "haproxy_server_up{instance=\"alekseibahmatov-2:9101\", server=\"agama-4\"}",
     "legendFormat": "agama-4"
    }
   ]
  },
  {
   "title": "Mysql Select queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"alekseibahmatov-1:9104\", command=\"select\"}[1m]) * 100",
     "legendFormat": "Select alekseibahmatov-1"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"alekseibahmatov-2:9104\", command=\"select\"}[1m]) * 100",
     "legendFormat": "Select alekseibahmatov-2"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"alekseibahmatov-1:9113\"}[1m]) * 100",
     "legendFormat": "alekseibahmatov-1"
    },
    {
     "expr": "rate(nginx_http_requests_total{instance=\"alekseibahmatov-2:9113\"}[1m]) * 100",
     "legendFormat": "alekseibahmatov-2"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "cloudflare.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "cloudflare.com" }
     ]
    },
    {
     "alias": "google.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "alias": "twitter.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "twitter.com" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success{instance=\"alekseibahmatov-3:9424\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok{instance=\"alekseibahmatov-3:9424\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}