{
 "title": "Mysql dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Mysql Status AB-2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"alekseibahmatov-2:9104\", job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql Select queries per minute AB-2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"alekseibahmatov-2:9104\", command=\"select\"}[1m]) * 100",
     "legendFormat": "Select"
    }
   ]
  },
  {
   "title": "Mysql Select queries per minute AB-2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"alekseibahmatov-2:9104\", command=\"select\"}[1m]) * 100",
     "legendFormat": "Select"
    }
   ]
  },
  {
   "title": "Mysql ServerID AB-2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{instance=\"alekseibahmatov-2:9104\", job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql ReadOnly AB-2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=\"alekseibahmatov-2:9104\", job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql Status AB-1",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"alekseibahmatov-1:9104\", job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql Select queries per minute AB-1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"alekseibahmatov-1:9104\", command=\"select\"}[1m]) * 100",
     "legendFormat": "Select"
    }
   ]
  },
  {
   "title": "Mysql ServerID AB-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{instance=\"alekseibahmatov-1:9104\", job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql ReadOnly AB-1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=\"alekseibahmatov-1:9104\", job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}