- name: Create directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    mode: '0755'

- name: Download agama.py
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /opt/agama/
    mode: '0755'
  loop:
    - https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    - https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile

- name: Build agama image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Run agama image
  community.docker.docker_container:
    name: agama-1
    image: agama
    restart_policy: always
    published_ports: "{{ agama_port }}:8000"
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}

- name: Run agama image
  community.docker.docker_container:
    name: agama-2
    image: agama
    restart_policy: always
    published_ports: "{{ agama_port + 1 }}:8000"
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}