- name: Add new user
  ansible.builtin.user:
    name: agama
    group: admin

- name: Create directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    mode: '0755'

- name: Install dependencies
  ansible.builtin.apt:
    name: 
      - python3-flask-sqlalchemy
      - python3-pymysql
    state: latest

- name: Download agama.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: '0755'
