- name: Create user 'backup'
  ansible.builtin.user:
    name: backup
    comment: User for backup
    group: backup
    home: /home/backup
    move_home: yes

- name: Create a 2048-bit SSH key for user backup in ~backup/.ssh/id_rsa
  ansible.builtin.user:
    name: backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Copy known_hosts file
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup