- name: Create prometheus directory
  ansible.builtin.file:
    path: /var/lib/prometheus
    recurse: yes
    state: directory

- name: Copy my.cnf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify: Restart mysqld exporter

- name: Install mysql exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    state: latest

- name: Copy prometheus-mysqld-exporter config
  ansible.builtin.template:
    src: prometheus-mysqld-exporter.j2
    dest: /etc/default/prometheus-mysqld-exporter
  notify: Restart mysqld exporter

- name: Enable mysql exporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
