- name: Install mysql server
  ansible.builtin.apt:
    name: mysql-server
    state: latest

- name: Copy mysql config
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql

- name: Start and enable mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql
    state: latest

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Prometheus MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
