- name: Install bind exporter
  ansible.builtin.apt:
    name: prometheus-bind-exporter
    state: latest

- name: Start and enable bind exporter
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes