- name: Create directory
  ansible.builtin.file:
    path: /etc/keepalived
    state: directory

- name: Copy config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Create user 'keepalived_script'
  ansible.builtin.user:
    name: keepalived_script

- name: Copy script
  ansible.builtin.copy:
    src: script.sh
    dest: /home/keepalived_script/script.sh
    owner: keepalived_script
    mode: '0755'

- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: latest

- name: Start and enable keepalived
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: yes