- name: Install keepalived exporter
  ansible.builtin.get_url:
    url: http://backup/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /tmp/keepalived-exporter.tar.gz

- name: Unpack keepalived exporter
  ansible.builtin.unarchive:
    src: /tmp/keepalived-exporter.tar.gz
    dest: /usr/local/bin

- name: Copy keepalived exporter service file
  ansible.builtin.copy:
    src: prometheus-keepalived-exporter.service
    dest: /etc/systemd/system/prometheus-keepalived-exporter.service
  notify: Restart keepalived exporter