- name: Install haproxy exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter

- name: Copy haproxy exporter config
  ansible.builtin.copy:
    src: prometheus-haproxy-exporter
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart haproxy exporter