- name: Install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: latest

- name: Start and enable prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes

- name: Change prometheus file
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Restart prometheus

- name: Change config file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart prometheus