- name: Install prometheus nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter
    state: latest

- name: Start and enable nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes