- name: Setup bind9
  ansible.builtin.apt:
    name: bind9
    state: latest

- name: Start and enable bind9 service
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

- name: Copy named.conf.options 
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Copy named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: Copy db.torchify.io
  ansible.builtin.template:
    src: db.torchify.io.j2
    dest: /var/lib/bind/db.torchify.io
  notify: Restart bind9

- name: Copy resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
